package com.springMvcPractice.domain.model;

public class Emplist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emplist.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emplist.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emplist.namekana
     *
     * @mbg.generated
     */
    private String namekana;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emplist.id
     *
     * @return the value of emplist.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emplist.id
     *
     * @param id the value for emplist.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emplist.name
     *
     * @return the value of emplist.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emplist.name
     *
     * @param name the value for emplist.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emplist.namekana
     *
     * @return the value of emplist.namekana
     *
     * @mbg.generated
     */
    public String getNamekana() {
        return namekana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emplist.namekana
     *
     * @param namekana the value for emplist.namekana
     *
     * @mbg.generated
     */
    public void setNamekana(String namekana) {
        this.namekana = namekana == null ? null : namekana.trim();
    }
}