spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password: test
  sql:
    init:
      platform: h2
      mode: never
      schema-locations: classpath:h2/schema_person.sql
  h2:
    console:
      enabled: true
hello:
  text: hello





