package com.springMvcPractice.domain.mapper;

import com.springMvcPractice.domain.model.Emplist;
import com.springMvcPractice.domain.model.EmplistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmplistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    long countByExample(EmplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    int deleteByExample(EmplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    int insert(Emplist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    int insertSelective(Emplist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    List<Emplist> selectByExample(EmplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    Emplist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Emplist record, @Param("example") EmplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Emplist record, @Param("example") EmplistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Emplist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emplist
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Emplist record);
}